### ISSUE TITLE
Convite

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#1]
### Banco de dados
- [x] Codigo do subevento
- [x] Codigo do convidado
- [x] Aceitou em 
- [x] Declinou em
- [x] Enviado em
- [x] Recebido em
- [x] Check-in em

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/46701504-46803200-cbf6-11e8-8747-94e42cdc8d9b.png)

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  Codigo do subevento
- [ ]   Codigo do convidado
- [ ]   Aceitou em
- [ ]   Declinou em
- [ ]   Enviado em
- [ ]   Recebido em
- [ ]   Check-in em
