### ISSUE TITLE
As vezes ao clicar em uma pessoa após efetuar o filtro está dando erro

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/eventos#113]
![image](https://user-images.githubusercontent.com/20132028/48004498-725cdd80-e0f8-11e8-9dd8-f2ac88291f6c.png)

Log do Erro

[erro.log](https://github.com/alerj/eventos/files/2548854/erro.log)

**Comment by antonioribeiro** [comment]
Já estava resolvido.
