### ISSUE TITLE
Enviar convites

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#121]
### Envio
- [x] Usar sistema de notificações do Laravel e enviar inicialmente por e-mail
- [x] Link de confirmação
- [x] Link de declinação
- [x] Ao declinar enviar e-mail sentindo muito
- [x] Ao confirmar enviar e-mail com o convite
- [x] Criar tabela para registrar notificação de envio para cada contato, se a pessoa tiver mais de um e-mail, por exemplo
- [x] Ao acrescentar novo contato de e-mail para uma pessoa, avisar de alguma forma que não foi enviado para aquele endereço
- [x] O status de recebido deve estar relacionado à tabela acima
- [x] Enviar PDF da credencial de estacionamento junto com o PDF do convite pro evento
- [x] Criar botão para envio de convites em massa no evento

### Events
- [x] Eviar e-mail com convite para o convidado ao criar o convite, se o evento estiver confirmado
- [x] Quando um evento for confirmado, enviar todos os convites ainda não enviados
- [x] Ao criar um convite, enviar e-mail para o convidado, caso o evento esteja confirmado
- [ ] Ao criar/alterar um e-mail de uma pessoa na instituição, enviar convite caso seja convidado de evento

### Jobs
- [x] Reenviar e-mail do convite se recebeu e não aceitou ou declinou

**Comment by AlexandreFerreiraRJ** [comment]
- [x] Ao declinar enviar e-mail sentindo muito

**Comment by AlexandreFerreiraRJ** [comment]
- [ ] Ao acrescentar novo contato de e-mail para uma pessoa, avisar de alguma forma que não foi enviado para aquele endereço

**Comment by AlexandreFerreiraRJ** [comment]
- [x]  Ao criar/alterar um e-mail de uma pessoa na instituição, enviar convite caso seja convidado de evento

**Comment by AlexandreFerreiraRJ** [comment]
Feito!

**Comment by antonioribeiro** [comment]
- [ ] Ao criar/alterar um e-mail de uma pessoa na instituição, enviar convite caso seja convidado de evento

Não está funcionando
