### ISSUE TITLE
Editor Markdown para textos de convite e afins

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#122]
Para que deixemos o usuário formatar os convites, precisamos:

- [x] Editor WYSIWYG Markdown
- [x] Permitir a inclusão de dados variáveis do convidado, evento, subevento, etc. Por exemplo: {convidado_nome}, {evento_nome}, {subevento_nome}
- [x] Substituir os textarea do sobevento todos por este editor
- [x] Formatar data para nosso formato
- [x] Formatar hora para 00:00
- [x] Endereço: se não tiver número e complemento não separar com vírgulas

**tags**
- [x] {convidado_nome}
- [x] {convidado_nome_publico}
- [x] {evento_nome}
- [x] {subevento_nome}
- [x] {traje_nome}
- [x] {traje_descricao}
- [x] {data_evento}
- [x] {convidado_tratamento}
- [x] {data_evento} (na verdade subevento)
- [x] {hora_evento}
- [x] {setor_nome}
- [x] {local}
- [x] {convite_codigo}
- [x] {instituicao_nome}
- [x] {cargo} (na instituicao)
- [x] {convite_codigo}
- [x] {endereco_rua}
- [x] {endereco_numero}
- [x] {endereco_complemento}
- [x] {endereco_bairro}
- [x] {endereco_cidade}
- [x] {endereco_uf}
- [x] {endereco_cep}
- [x] {google_maps_link}
- [x] {google_maps_imagem} (url - pensar)
- [x] {endereco_completo} (tudo numa linha única)
- [x] {latitude}
- [x] {longitude}

**Comment by BMasquio** [comment]
> Para que deixemos o usuário formatar os convites, precisamos:
> 
> * [ ]  Editor WYSIWYG Markdown
> * [ ]  Permitir a inclusão de dados variáveis do convidado, evento, subevento, etc. Por exemplo: {convidado_nome}, {evento_nome}, {subevento_nome}
> * [ ]  Substituir os textarea do sobevento todos por este editor

> * [x]  {convidado_nome}
> * [x]  {convidado_nome_publico}
> * [x]  {evento_nome}
> * [x]  {subevento_nome}
> * [x]  {traje_nome}
> * [x]  {traje_descricao}
> * [x]  {data_evento}
> * [x]  {convidado_tratamento}
> * [x]  {data_evento} (na verdade subevento)
> * [x]  {hora_evento}
> * [x]  {setor_nome}
> * [x]  {local}
> * [x]  {convite_codigo}
> * [x]  {instituicao_nome}
> * [x]  {cargo} (na instituicao)
> * [x]  {convite_codigo}
> * [x]  {endereco_rua}
> * [x]  {endereco_numero}
> * [x]  {endereco_complemento}
> * [x]  {endereco_bairro}
> * [x]  {endereco_cidade}
> * [x]  {endereco_uf}
> * [x]  {endereco_cep}
> * [x]  {google_maps_link}
> * [ ]  {google_maps_imagem} (url - pensar)
> * [x]  {endereco_completo} (tudo numa linha única)
> * [x]  {latitude}
> * [x]  {longitude}

**Comment by BMasquio** [comment]
Achei um editor interessante
https://github.com/hinesboy/mavonEditor

Tem suporte para português e os botões são todos desabilitáveis.
![image](https://user-images.githubusercontent.com/15174854/49033427-55b34300-f196-11e8-879a-12ffc9028325.png)


O que acha, @antonioribeiro ?

**Comment by BMasquio** [comment]
> Para que deixemos o usuário formatar os convites, precisamos:
> 
> * [x]  Editor WYSIWYG Markdown
> * [x]  Permitir a inclusão de dados variáveis do convidado, evento, subevento, etc. Por exemplo: {convidado_nome}, {evento_nome}, {subevento_nome}
> * [x]  Substituir os textarea do sobevento todos por este editor
> * [x]  Formatar data para nosso formato
> * [x]  Formatar hora para 00:00
> * [x]  Endereço: se não tiver número e complemento não separar com vírgulas
> 
> **tags**
> 
> * [x]  {convidado_nome}
> * [x]  {convidado_nome_publico}
> * [x]  {evento_nome}
> * [x]  {subevento_nome}
> * [x]  {traje_nome}
> * [x]  {traje_descricao}
> * [x]  {data_evento}
> * [x]  {convidado_tratamento}
> * [x]  {data_evento} (na verdade subevento)
> * [x]  {hora_evento}
> * [x]  {setor_nome}
> * [x]  {local}
> * [x]  {convite_codigo}
> * [x]  {instituicao_nome}
> * [x]  {cargo} (na instituicao)
> * [x]  {convite_codigo}
> * [x]  {endereco_rua}
> * [x]  {endereco_numero}
> * [x]  {endereco_complemento}
> * [x]  {endereco_bairro}
> * [x]  {endereco_cidade}
> * [x]  {endereco_uf}
> * [x]  {endereco_cep}
> * [x]  {google_maps_link}
> * [x]  {google_maps_imagem} (url - pensar)
> * [x]  {endereco_completo} (tudo numa linha única)
> * [x]  {latitude}
> * [x]  {longitude}
