### ISSUE TITLE
Incluir campo traje no subevento

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#125]
- [x] Select (tabela: tipos de trajes)
- [x] Pegar a lista correta de trajes e fazer seed na migration

**Comment by antonioribeiro** [comment]
- [ ] Select (tabela: tipos de trajes)
- [ ] Pegar a lista correta de trajes e fazer seed na migration

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito
