### ISSUE TITLE
Finalizar evento

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#126]
- [x] Marcar evento como "acontecido" para que ele saia das buscas
- [x] Filtrar eventos para que não apareçam mais na lista (depois vamos ter que poder configurar isso)
- [x] Como é algo que vai fazer sumir os eventos, pedir uma segunda confirmação

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  Marcar evento como "acontecido" para que ele saia das buscas

- [ ] Filtrar eventos para que não apareçam mais na lista (depois vamos ter que poder configurar isso)

- [ ]  Como é algo que vai fazer sumir os eventos, pedir uma segunda confirmação

**Comment by antonioribeiro** [comment]
Feito pelo @BMasquio
