### ISSUE TITLE
Criar código do convite na tabela invitations

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#127]
- [x] Criar campo code e criar randomicamente o código com padrão AAA999
- [x] Criar campo uuid para ser usado nos endpoints

**Comment by AlexandreFerreiraRJ** [comment]
- [ ] Criar campo code e criar randomicamente o código com padrão AAA999

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/48091806-e333f080-e1f1-11e8-9ad4-217615203fc9.png)

**Comment by AlexandreFerreiraRJ** [comment]
- [ ] Criar campo uuid para ser usado nos endpoints

![image](https://user-images.githubusercontent.com/4698779/48092227-41ad9e80-e1f3-11e8-937a-8a0c682ce895.png)

**Comment by AlexandreFerreiraRJ** [comment]
Feito
