### ISSUE TITLE
Associar um subEvento a outro

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#136]
- [x] campo: associated_subevent_id
- [x] select com lista de subeventos em aberto
- [x] um subevento associado poderá ser, por exemplo, uma credencial de estacionamento

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  campo: associated_subevent_id
- [ ] select com lista de subeventos em aberto
- [ ] um subevento associado poderá ser, por exemplo, uma credencial de estacionamento

**Comment by AlexandreFerreiraRJ** [comment]
Feito
