### ISSUE TITLE
Pessoas

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#2]
- [x] name
- [x] nickname
- [x] title
- [x] cargo (deletar)
- [x] position_id
- [x] institution_id
- [x] party_id
- [x] birthdate
- [x] Telefone (deletar)
- [x] Email (deletar)
- [x] addresses (outra tabela)
- [x] contacts (outra tabela)
- [x] categories (outra tabela)

### CRU-D
- [x] model (laravel)
- [x] request create (laravel)
- [x] request update (laravel)
- [x] menu item
- [x] table
- [x] create
- [x] update
- [x] importar dados

**Comment by AlexandreFerreiraRJ** [comment]
Feito!

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  Nome
- [ ]   Com endereço
- [ ]   Cargo
- [ ]   Tratamento
- [ ]   Telefone
- [ ]   Email

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  birthdate

**Comment by AlexandreFerreiraRJ** [comment]
- [x] categories (outra tabela)
