### ISSUE TITLE
Partidos Políticos

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#20]
table: parties
- [x] name
- [x] abbreviation

outros a fazer
- [ ] carregar todos os atuais

### CRU-D
- [ ] model (laravel)
- [ ] request create (laravel)
- [ ] request update (laravel)
- [ ] menu item
- [ ] table
- [ ] create
- [ ] update
- [ ] importar dados

**Comment by orlandovinicius1987** [comment]
Fazendo

**Comment by orlandovinicius1987** [comment]
Falta carregar os dados atuais

**Comment by BMasquio** [comment]
Os partidos políticos vão ter contatos e endereços?

**Comment by antonioribeiro** [comment]
Sim, vão ter contatos e endereços
