### ISSUE TITLE
Título incorreto no form de Função

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#205]
Ao clicar em editar função de pessoa na instituição aparece "Novo Cargo"

- [x] Não é NOVO
- [x] Não temos "cargos", temos funções
- [x] Procurar no sistema inteiro, está assim em vários lugares

**Comment by antonioribeiro** [comment]
É isso que mostra ao editar a função

![image](https://user-images.githubusercontent.com/3182864/48384670-8abd9100-e6d2-11e8-981a-45f3f801db33.png)

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito
