### ISSUE TITLE
Página trava ao tentar editar um endereço sem latitude e longitude

### ISSUE THREAD

**Issue by BMasquio** [alerj/eventos#221]
![image](https://user-images.githubusercontent.com/15174854/48422471-dcebca00-e745-11e8-9c20-df67222b0d9b.png)

![image](https://user-images.githubusercontent.com/15174854/48422575-1a505780-e746-11e8-87d9-51ab2ae63a83.png)

**Comment by antonioribeiro** [comment]
Resolvido.
