### ISSUE TITLE
Tipos de Contatos

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#23]
- [x] table: contacts_types
- [x] name
- [x] fazer um seed básico

### CRU-D
- [x] model (laravel)
- [x] request create (laravel)
- [x] request update (laravel)
- [x] menu item
- [x] table
- [x] create
- [x] update
- [x] importar dados

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
> * [x]  table: contacts_types
> * [x]  name
> * [x]  fazer um seed básico

Feito
