### ISSUE TITLE
Assessores

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#24]
- [x] table: advisors
- [x] name
- [x] advisor_type_id 
- [x] person_id

tabelas auxiliares
--------------------------
- [ ] contatos (pivot polimorfico)
- [ ] tipos de assessores

### CRU-D
- [ ] model (laravel)
- [ ] request create (laravel)
- [ ] request update (laravel)
- [ ] menu item
- [ ] table
- [ ] create
- [ ] update
- [ ] importar dados

**Comment by orlandovinicius1987** [comment]
Feito

**Comment by BMasquio** [comment]
- [x] person_id
