### ISSUE TITLE
Tipos de Assessores

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#27]
- [x] table: advisors_types
- [x] name

### CRU-D
- [ ] model (laravel)
- [ ] request create (laravel)
- [ ] request update (laravel)
- [ ] menu item
- [ ] table
- [ ] create
- [ ] update
- [ ] importar dados

**Comment by orlandovinicius1987** [comment]
feito

**Comment by antonioribeiro** [comment]
passou a ser role
