### ISSUE TITLE
Refatorar o controller de invitation

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#294]
- [x] Tem código demais no método (de Controller) acceptable, mover as condicionais pra dentro do repositório
- [x] Substituir UUID por id
- [x] Controller usado está errado, os controllers dentro de Api são para coisas relacionadas a Api, que retornam um resultado JSON sempre, este controller não é de Http normal e portanto retorna HTML como resultado
- [x] A mensagem que a pessoa vai ver não deve ser mostrada via flash message, devem ir como uma mensagem normal no corpo da view.
- [x] Pode fazer views separadas e diferentes para estas mensagens e dar um redirect para ela, são mensagens pequenas, eu sei, mas depois a gente resolve de outra maneira.
- [ ] Como o usuário não poderá fazer mais nada depois disso, a URL de redirect não deve conter dados como os códigos das tabelas. Quando menos informação sobre dados internos do sistema melhor.
- [x] Não consegui entender o que faz aquele Invitations@acceptable, parece que foi deixado pra trás parte do código que era usado na app em Vue
- [x] Também remover de dentro de api/v1/, pois não se trata de Api

**Comment by antonioribeiro** [comment]
Já estou trocando o uuid por id

**Comment by AlexandreFerreiraRJ** [comment]
- [ ] Tem código demais no método (de Controller) acceptable, mover as condicionais pra dentro do repositório

**Comment by AlexandreFerreiraRJ** [comment]
- [ ] Controller usado está errado, os controllers dentro de Api são para coisas relacionadas a Api, que retornam um resultado JSON sempre, este controller não é de Http normal e portanto retorna HTML como resultado

**Comment by AlexandreFerreiraRJ** [comment]
87% pronto

**Comment by AlexandreFerreiraRJ** [comment]
Feito 100%

![image](https://user-images.githubusercontent.com/4698779/49144767-4db5e900-f2e5-11e8-8107-532146ec4912.png)
