### ISSUE TITLE
Filtros em convites

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#312]
Criar checkboxes como o que já tem hoje para e-mails:

- [x] não recebido
- [x] não aceito
- [x] não respondido
- [x] não fez check-in
- [x] não enviado
- [x] conviteNaoEnviado = notSent
- [x] conviteNaoRecebido = notReceived
- [x] conviteNaoAceito = notAccepted
- [x] conviteNoCheckIn = notCheckedIn
- [x] conviteNaoRespondido = notAnswered

**Comment by AlexandreFerreiraRJ** [comment]
Fazendo

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  não enviado
- [ ]  não recebido
- [ ]  não aceito
- [ ]  não fez check-in
- [ ]  não respondido

**Comment by AlexandreFerreiraRJ** [comment]
- [ ] conviteNaoEnviado = notSent
 - [ ] conviteNaoRecebido = notReceived
 - [ ] conviteNaoAceito = notAccepted
 - [ ] conviteNoCheckIn = notCheckedIn
 - [ ] conviteNaoRespondido = notAnswered
