### ISSUE TITLE
O tratamento da pessoa está errado

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#314]
Está assim no e-mail

![image](https://user-images.githubusercontent.com/3182864/49117589-57f5ca00-f288-11e8-8b8a-95743198c2ee.png)

Mas era pra ter vindo o do person_institution:

![image](https://user-images.githubusercontent.com/3182864/49117602-66dc7c80-f288-11e8-9d2f-533613a82c30.png)

**Comment by AlexandreFerreiraRJ** [comment]
Procurei e não achei os arquivos  que fazem o email. Pode me dizer onde ficam?

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito
