### ISSUE TITLE
Erro na URL de endereços

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/eventos#344]
Ao criar um sub-evento, há um tabela com Endereços disponíveis, ao clicar para edita-los a URL não está correta.

![image](https://user-images.githubusercontent.com/4698779/49225401-1c174d80-f3cb-11e8-8a67-f7701e3b5f14.png)

http://eventos.com/admin#/events/4/sub-events/events/{events.selected.id}/sub-event/4/addresses/644/update

**Comment by BMasquio** [comment]
Feito
