### ISSUE TITLE
Lista de convidáveis está na ordem errada

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/eventos#350]
![image](https://user-images.githubusercontent.com/4698779/49226871-e5dbcd00-f3ce-11e8-8b1f-a51fbc159fac.png)

**Comment by antonioribeiro** [comment]
Listar por nome. Teoricamente a lista já deveria estar, mas deve ter bug.

**Comment by AlexandreFerreiraRJ** [comment]
Feito

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/49291153-67dffa80-f490-11e8-9236-9af538f6d401.png)
