### ISSUE TITLE
Erro na pagina de evento

### ISSUE THREAD

**Issue by Hugogemino** [alerj/eventos#361]
![image](https://user-images.githubusercontent.com/40171645/49244085-18e58700-f3f6-11e8-8bc0-fd2b8a95310a.png)
![image](https://user-images.githubusercontent.com/40171645/49244118-2d298400-f3f6-11e8-99a1-3d513ca90573.png)
![image](https://user-images.githubusercontent.com/40171645/49244142-387caf80-f3f6-11e8-8f9a-28b5f431e5d3.png)

**Comment by AlexandreFerreiraRJ** [comment]
Não consegui reproduzir
