### ISSUE TITLE
"Convite já aceito" / "Convite já declinado"

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#372]
Se a pessoa tentar (no e-mail recebido) aceitar ou declinar novamente um convite:

- [x] Avisar que já foi aceito ou declinado e que ele/a vai receber as credenciais novamente
- [x] Reenviar as credenciais

**Comment by BMasquio** [comment]
No momento, não é possível fazer isso. Os botão de aceitar só vai aparecer se não tiver sido rejeitado e o de rejeitado só vai aparecer se o convite não tiver sido aceito.

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito.

Não está reenviando credenciais por regras de negócio, mas está mostrando mensagens que o convite já foi aceito/declinado.
