### ISSUE TITLE
Mensagens de erros estão mal posicionadas

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/eventos#379]
![image](https://user-images.githubusercontent.com/4698779/49307984-0a62a280-f4be-11e8-88d0-9ca8f9271363.png)

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/49308041-367e2380-f4be-11e8-80a5-5cafbaf24cb5.png)

**Comment by AlexandreFerreiraRJ** [comment]
@brenot

**Comment by brenot** [comment]
https://github.com/alerj/eventos/pull/490

**Comment by antonioribeiro** [comment]
Resolvido
