### ISSUE TITLE
Erro ao entrar na página de Eventos

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/eventos#385]
![image](https://user-images.githubusercontent.com/20132028/49313259-dbecc380-f4cd-11e8-9fe6-8ae2e05bb5fb.png)

Ao entrar na página de Eventos, o erro acontecia.

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/49313376-2f5f1180-f4ce-11e8-87d5-5ffc10b1e287.png)
