### ISSUE TITLE
Filtro de invitables

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#421]
- [x] Funções
- [x] Instituições
- [ ] Testar bem esse filtro porque parece que às vezes ele não funciona, ou demora muito
- [ ] Se estiver demorando, tentar entender o motivo da demora

**Comment by orlandovinicius1987** [comment]
- [X] Funções
- [X] Instituições

**Comment by orlandovinicius1987** [comment]
- [X] Testar bem esse filtro porque parece que às vezes ele não funciona, ou demora muito

Fiz combinação de filtros e o mesmo funcionou corretamente.
