### ISSUE TITLE
Apagar o filtro de invitables ao sair do InviteForm

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#422]

**Comment by orlandovinicius1987** [comment]
Investigando

**Comment by antonioribeiro** [comment]
@orlandovinicius1987, você chegou a fazer isso? Lembro que tínhamos falado algo a respeito...

**Comment by antonioribeiro** [comment]
@orlandovinicius1987 , você chegou a terminar isso?

**Comment by orlandovinicius1987** [comment]
Subiu junto com o contador
