### ISSUE TITLE
Busca não funcionou com a nome da Bruna

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#424]
Em invitables:

- [x] Mostrar todos, inclusive convidados
- [x] Remover checkbox
- [x] Colocar um badge indicando que já está convidado
- [x] Adicionar um checkbox para esconder os já convidados

**Comment by BMasquio** [comment]
Acredito que seja relacionado a #444

**Comment by BMasquio** [comment]
> Em invitables:
> 
> * [x]  Mostrar todos, inclusive convidados
> * [x]  Remover checkbox
> * [x]  Colocar um badge indicando que já está convidado
> * [ ]  Adicionar um checkbox para esconder os já convidados

**Comment by BMasquio** [comment]
> Em invitables:
> 
> * [x]  Mostrar todos, inclusive convidados
> * [x]  Remover checkbox
> * [x]  Colocar um badge indicando que já está convidado
> * [x]  Adicionar um checkbox para esconder os já convidados

**Comment by BMasquio** [comment]
Feito
