### ISSUE TITLE
Emails com campos de email inválidos

### ISSUE THREAD

**Issue by BMasquio** [alerj/eventos#449]
Eu sei que são chefes de gabinete e provavelmente não vão ser convidados para nenhum evento, mas se forem, dará um bug na hora de enviar o email. Deu nos testes que estava fazendo.

Luiz Aromatis e Ana Helena.

![image](https://user-images.githubusercontent.com/15174854/49441627-46438380-f7ae-11e8-8075-06e0bc00f563.png)

![image](https://user-images.githubusercontent.com/15174854/49441655-5d827100-f7ae-11e8-9bc7-c1e837bc488f.png)

**Comment by antonioribeiro** [comment]
Resolvido
