### ISSUE TITLE
Erro ao tentar incluir uma função para uma pessoa

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#454]
![image](https://user-images.githubusercontent.com/3182864/49458720-86b5f800-f7d4-11e8-8043-b5d30b18146b.png)

![image](https://user-images.githubusercontent.com/3182864/49458761-9b928b80-f7d4-11e8-9ecf-1de2f405bd59.png)

**Comment by BMasquio** [comment]
Aconteceu uma vez comigo também, mas depois funcionou normalmente

**Comment by orlandovinicius1987** [comment]
Tentando reproduzir o erro e não estou conseguindo
