### ISSUE TITLE
Formatar CPF no aceite do convite

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#457]
- [ ] Não precisa colocar máscara agora no form
- [ ] Formatar na hora de gravar no banco de dados

Se já estiver feito desconsiderar apenas avise aqui para eu fechar.

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito

**Comment by BMasquio** [comment]
> * [x]  Não precisa colocar máscara agora no form
> * [x]  Formatar na hora de gravar no banco de dados
