### ISSUE TITLE
Está fazendo requisições demais via pesquisa de pessoa

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#491]
Ao digitar qualquer coisa na pesquisa de pessoa ele fica tentando baixar a foto várias vezes

![image](https://user-images.githubusercontent.com/3182864/49599341-e0026080-f967-11e8-8aa7-5420b37fd151.png)

**Comment by BMasquio** [comment]
Fazendo

**Comment by AlexandreFerreiraRJ** [comment]
Feito
