### ISSUE TITLE
Envio de credencial

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#5]
- [x] Envio por e-mail
- [x] Design da credencial
- [x] Dados da pessoa
- [x] QRCode
- [x] Link do google maps
- [x] https://www.google.com.br/maps/place...
- [x] Listar as credenciais que o convidado está recebendo
- [x] Acrescentar endereços
- [x] Link do google para cada credencial
- [x] Traje e descritivo do mesmo

**Comment by BMasquio** [comment]
> * [x]  QRCode
