### ISSUE TITLE
Bug ao inserir contato

### ISSUE THREAD

**Issue by BMasquio** [alerj/eventos#523]
Em produção, o cliente reclamou que ao inserir emails ou telefones, a tela voltava normalmente para a anterior, mas não aparecia o contato inserido. Ela tentou de novo e conseguiu.

Talvez esses contatos tenham ficado duplicados no banco e possa ter havido problema na atualização da lista só.

**Comment by antonioribeiro** [comment]
Está funcionando, é algo relacionado com a aplicação que não está sendo recarregada.
