### ISSUE TITLE
Está aceitando cadastrar e-mails com espaços

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#563]
- [x] Proteger
- [x] Dar um trim em toda a base de contatos

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Tinha alguns emails com espaços no meu banco e fiz a migration.
Fiz um sanitize que dá um trim nos contacts, apesar de que de alguma forma, as requisições já estavam sendo mandadas sem os espaços, pois o regex que valida o email rejeita se houver esses espaços.

**Comment by BMasquio** [comment]
Feito
