### ISSUE TITLE
Checkbox de selecionar cliente só pode aparecer para quem tem acesso a mais de um

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#603]
Só uma verificação, não se já está assim ou não, mas me ocorreu agora.

Quem é do Forum, por exemplo, não vai poder ter acesso a nada que é do Cerimonial, então nem precisa aparecer o checkbox pra eles

**Comment by antonioribeiro** [comment]
Quem é do Forum, por exemplo, não vai poder ter acesso a nada que é do Cerimonial, então nem precisa aparecer o checkbox pra eles

**Comment by antonioribeiro** [comment]
Tem umas pendências nesta PR relacionado a isso: https://github.com/alerj/eventos/pull/588

**Comment by AlexandreFerreiraRJ** [comment]
Algumas coisas aqui:

- [ ]  voltar esses arquivos que estão conflitando, removê-los dos commits, que não eram pra estar nesse pull request de qualquer forma, mas sei que foi na "entre-safra" das mudanças

- [ ]  eu pretendo fazer merge disso assim que a gente conseguir testar bem, visto que isso pode quebrar muita coisa, mas o master está indo pra produção agora, então não vou poder fazer merge no master

- [ ]  tem uma outra issue sobre o checkbox aparecer pra todos ou só pra quem tem acesso a mais de um cliente

**Comment by AlexandreFerreiraRJ** [comment]
Feito
