### ISSUE TITLE
Criar tabela de assuntos

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#669]
- [x] Table: topics
- [x] Criar CRUD
- [x] Associar: Person is "interested in" topics
- [x] Associar: Person_institution is "interested in" topics (talvez também, temos que pensar)

**Comment by orlandovinicius1987** [comment]
Iniciando

**Comment by orlandovinicius1987** [comment]
- [X] Table: topics
- [X] Criar CRUD
- [ ]  Associar: Person is "interested in" topics
- [ ]  Associar: Person_institution is "interested in" topics (talvez também, temos que pensar)
