### ISSUE TITLE
Criar campo para arquivo do convite

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#675]
- [ ] invitation_file (/images/invitations/2019-01-posse-governador.jpg)
- [ ] Ainda não vamos fazer a parte de anexar arquivos porque isso será meio demorado
- [ ] O arquivo do convite deverá ser colocado manualmente (via git) no repositório por enquanto
- [ ] O nome do arquivo deverá ser relativo à pasta public e vamos colocar a gente mesmo manualmente por enquanto
- [ ] O arquivo deverá ser incluído no corpo do e-mail de convite e também deve ser anexado (isso já está pronto, já é assim hoje, só o que vai mudar é o nome do arquivo)
- [ ] Criar a tag "arquivo_convite" para ser usada na edição do texto do convite

**Comment by BMasquio** [comment]
O campo invitation_file vai conter o que exatamente? Uma string com o caminho pro arquivo ou o blob em si?

**Comment by antonioribeiro** [comment]
O nome do arquivo relativo à pasta public, como falei também mais acima. Coloquei um exemplo lá agora também

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito
A imagem por enquanto tem que estar no formato png
