### ISSUE TITLE
Está permitindo incluir mais de uma pessoa com o mesmo CPF

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#681]

**Comment by AlexandreFerreiraRJ** [comment]
@brenot 
Favor ajustar o layout dessa página

![image](https://user-images.githubusercontent.com/4698779/51390609-e7945800-1b16-11e9-8cf0-f5cd10250d9e.png)

![image](https://user-images.githubusercontent.com/4698779/51390632-f24eed00-1b16-11e9-84e4-b13682f2da94.png)

> resources/js/components/app/Input.vue

![image](https://user-images.githubusercontent.com/4698779/51390661-0a267100-1b17-11e9-8adc-727e429c354a.png)

**Comment by AlexandreFerreiraRJ** [comment]
Feito

**Comment by antonioribeiro** [comment]
Isso já tinha sido feito: https://github.com/alerj/eventos/issues/520
