### ISSUE TITLE
Ao criar subevento os endereços estão repetindo

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#709]
- [ ] Remover as repetições
- [ ] Transformar em um select para ocupar apenas uma linha

![image](https://user-images.githubusercontent.com/3182864/51478748-7b626000-1d73-11e9-9543-0814fd297128.png)

**Comment by antonioribeiro** [comment]
Estes não são endereços de subeventos e sim, provavelmente, de pessoas

**Comment by AlexandreFerreiraRJ** [comment]
Agora já são os de eventos.
![image](https://user-images.githubusercontent.com/4698779/52223580-163b5e00-288d-11e9-9eac-ca12058a3263.png)

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/52223675-484cc000-288d-11e9-9200-3bc4fb52168c.png)
![image](https://user-images.githubusercontent.com/4698779/52223698-53075500-288d-11e9-82ca-842e434aaea7.png)

**Comment by AlexandreFerreiraRJ** [comment]
[x] - Remover as repetições
[x] - Transformar em um select para ocupar apenas uma linha

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/52870784-c92e7600-312f-11e9-85ab-a392968d00a8.png)


![image](https://user-images.githubusercontent.com/4698779/52870815-d64b6500-312f-11e9-9890-05f5932b5ba9.png)
