### ISSUE TITLE
Está deixando criar Subevento sem Setor

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#712]

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/51486499-f9306680-1d87-11e9-8096-b716fea83662.png)

**Comment by AlexandreFerreiraRJ** [comment]
Feito!

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/51492298-824f9980-1d98-11e9-890a-03a94aae68c0.png)
