### ISSUE TITLE
Mudar sistema de permissionamento

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#714]
Hoje nós usamos o permissionamento desta maneira:

- administrador
- cerimonial
- receptivo
- forum

Se a gente quiser cadastrar uma pessoa como

- Administrador + Forum
- Receptivo + Cerimonial

Que é o que a gente precisa para que o Forum entre, não vai dar. Assim, precisamos mudar o sistema de permissionamento para as permissões incluirem também o cliente:

- administrador - forum
- cerimonial - receptivo

E, claro, fazer um parse dessa string para retirar dela o permissionamento e o cliente.

**Comment by BMasquio** [comment]
Fazendo

**Comment by antonioribeiro** [comment]
@BMasquio, fiz as modificações que eu entendi como sendo necessárias e já dei merge de tudo no repositório, baixa e testa isso por favor?

**Comment by BMasquio** [comment]
Ok
