### ISSUE TITLE
Possibilitar máscara de telefone que inclui código do país

### ISSUE THREAD

**Issue by BMasquio** [alerj/eventos#767]
Permitir como opção, além das outras já existentes, essa máscara com código.

Exemplo

(21)98765-4321 => +55(21)98765-4321

**Comment by antonioribeiro** [comment]
Marcado como bug porque os usuários do Fórum não estão conseguindo digitar os telefones do jeito que eles preferem, que é com código do país.

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito
