### ISSUE TITLE
Ao enviar e-mail, remover endereços duplicados

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#807]

**Comment by BMasquio** [comment]
Pelo que imagino, está se dois subeventos acontecem em um mesmo lugar, ele está anexando os dois duplicados no e-mail. É isso?

**Comment by antonioribeiro** [comment]
Provavelmente mais simples que isso, quando envia um convite (subevento 1) a pessoa tem emails repetidos gerados na importação, os e-mails duplicados não foram removidos, então ele manda a mensagem para a pessoa mais de uma vez.

Assim, ao listar os e-mails a serem enviados, remover as duplicidades.

Acho que temos que tirar essas duplicidades do banco de dados também, mas é meio preocupante porque a mesma pessoas em duas instituições diferentes está com o mesmo e-mail, mas isso tem que manter assim para elas acertarem depois.
