### ISSUE TITLE
Bug na exportação

### ISSUE THREAD

**Issue by BMasquio** [alerj/eventos#876]
Ao selecionar uma instituição e tentar exportar todos os emails.

> [2019-05-21 12:38:15] local.ERROR: SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference "id" is ambiguous
> LINE 1: ...s"."contact_type_id" = "contact_types"."id" where "id" in (s...
>                                                              ^ (SQL: select count(*) as aggregate from "people" left join "person_institutions" on "people"."id" = "person_institutions"."person_id" left join "institutions" on "person_institutions"."institution_id" = "institutions"."id" left join "person_institutions" as "advisors" on "advisors"."advised_id" = "person_institutions"."id" left join "contacts" on "contacts"."person_institution_id" = "person_institutions"."id" left join "contact_types" on "contacts"."contact_type_id" = "contact_types"."id" where "id" in (select "person_id" from "person_institutions" inner join "institutions" on "institutions"."id" = "person_institutions"."institution_id" where "institutions"."id" = 875) and "people"."client_id" = 2 and "people"."is_active" = 1) {"userId":11,"email":"bmasquio@alerj.rj.gov.br","exception":"[object] (Illuminate\\Database\\QueryException(code: 42702): SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference \"id\" is ambiguous
> LINE 1: ...s\".\"contact_type_id\" = \"contact_types\".\"id\" where \"id\" in (s...
>                                                              ^ (SQL: select count(*) as aggregate from \"people\" left join \"person_institutions\" on \"people\".\"id\" = \"person_institutions\".\"person_id\" left join \"institutions\" on \"person_institutions\".\"institution_id\" = \"institutions\".\"id\" left join \"person_institutions\" as \"advisors\" on \"advisors\".\"advised_id\" = \"person_institutions\".\"id\" left join \"contacts\" on \"contacts\".\"person_institution_id\" = \"person_institutions\".\"id\" left join \"contact_types\" on \"contacts\".\"contact_type_id\" = \"contact_types\".\"id\" where \"id\" in (select \"person_id\" from \"person_institutions\" inner join \"institutions\" on \"institutions\".\"id\" = \"person_institutions\".\"institution_id\" where \"institutions\".\"id\" = 875) and \"people\".\"client_id\" = 2 and \"people\".\"is_active\" = 1) at /Users/brunomasquio/code/eventos/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671, Doctrine\\DBAL\\Driver\\PDOException(code: 42702): SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference \"id\" is ambiguous
> LINE 1: ...s\".\"contact_type_id\" = \"contact_types\".\"id\" where \"id\" in (s...
>                                                              ^ at /Users/brunomasquio/code/eventos/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 42702): SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference \"id\" is ambiguous
> LINE 1: ...s\".\"contact_type_id\" = \"contact_types\".\"id\" where \"id\" in (s...
>                                                              ^ at /Users/brunomasquio/code/eventos/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)

![image](https://user-images.githubusercontent.com/15174854/58110538-1b1ae800-7bc6-11e9-8788-744b479ff482.png)

**Comment by antonioribeiro** [comment]
Resolvido
