### ISSUE TITLE
Receptivo - Dia do evento

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#9]
- [x] Tela de recepção
- [x] Leitura do QRCode (browser celular e web)
- [x] Contagem de convidados / confirmados / recepcionados
- [x] Email de agradecimento por comparecer
- [x] Permitir digitação manual do código do convite
- [x] Não deixar a pessoa entrar duas vezes no evento, avisar à/ao recepcionista

**Comment by BMasquio** [comment]
Fazendo a tabela no Dashboard de subeventos

**Comment by orlandovinicius1987** [comment]
- [X] Contagem de convidados / confirmados / recepcionados
