### ISSUE TITLE
Fazer upload de arquivos (convites)

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#911]
- [x] Tabela: uploaded_files
- [x] Arquivos armazenado em storage/app/files
- [x] Usar o mesmo upload (VueJS) do DOCIGP
- [x] Criar um form com os arquivos enviados pelo cliente
- [x] Botão para visualização da imagem
- [x] Botão para copiar o link relativo da imagem (que será colado no sub-evento)

**Comment by BMasquio** [comment]
Fazendo

**Comment by BMasquio** [comment]
Feito

#913
