### ISSUE TITLE
Está permitindo convidar pessoas inativadas (na instituição)

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/eventos#921]

**Comment by BMasquio** [comment]
Quando uma instituição estiver inativa, não pode convidar PersonInstitution dessa instituição, certo?

**Comment by antonioribeiro** [comment]
Isso aí! Acho que isso já tinha sido feito, não sei o motivo de não estar funcionando. Deve ser o filtro. Mas tem que reforçar isso na validação ou na rotina de convites...
